### ISSUE TITLE
Setting defaultFoldingRangeProvider breaks folding in files with no rules set

### ISSUE THREAD

**Issue by paul-uz** [zokugun/vscode-explicit-folding#108]
If I set `editor.defaultFoldingRangeProvider` to `zokugun.explicit-folding` as suggested, my rule for YAML files works, but then folding in my Typescript files is removed.

Settings

```
"explicitFolding.rules": {
        "YAML": [
            {
                "begin": "#region",
                "end": "#endregion"
            }
        ]
    },
```

**Comment by daiyam** [comment]
Use the language selector of vscode:
```
"[yaml]": {
    "explicitFolding.rules": [
        {
            "begin": "#region",
            "end": "#endregion"
        }
    ],
},
```

**Comment by daiyam** [comment]
Sorry, I've badly read your issue...

> If I set editor.defaultFoldingRangeProvider to zokugun.explicit-folding as suggested, my rule for YAML files works, but then folding in my Typescript files is removed.

Yes, it's the expected behaviour. I've added a disclaimer in settings example.

**Comment by paul-uz** [comment]
> Sorry, I've badly read your issue...
> 
> > If I set editor.defaultFoldingRangeProvider to zokugun.explicit-folding as suggested, my rule for YAML files works, but then folding in my Typescript files is removed.
> 
> Yes, it's the expected behaviour. I've added a disclaimer in settings example.

Well that's pretty crap expected behaviour then. Needless to say I uninstalled this plugin as it's more trouble than it's worth.

**Comment by daiyam** [comment]
Thank for the support and the thoughtlessness. It is a gift.
