### ISSUE TITLE
additionalSchemes not working

### ISSUE THREAD

**Issue by mDeSimone-DFactorySrl** [zokugun/vscode-explicit-folding#114]
## Describe the issue
i am trying to add an additional scheme with "begin": "{/*", "end": "*/}" but in my .tsx file seems not working

## To reproduce

- VSCode: 1.88.1
- Explicit Folding: v0.23.1
- Language: Typescript
- Language Provider: 

### Code Example
```
{/* #region Test */}
<Text>Random Text</Text>
{/* #endregion */}
```

### Settings
```
"editor.showFoldingControls": "always",
    "explicitFolding.rules": {
        "*": {
            "begin": "{/*",
            "end": "*/}"
        }
    },
```

**Comment by daiyam** [comment]
In general, VSCode doesn't support single line folding. Same for this extension. (Since it provides only the ranges and doesn't change the UI behavior)

**Comment by daiyam** [comment]
Maybe you should try:
```
"explicitFolding.rules": {
        "*": {
            "begin": "#region",
            "end": "#endregion"
        }
    },

**Comment by mDeSimone-DFactorySrl** [comment]
> In general, VSCode doesn't support single line folding. Same for this extension. (Since it provides only the ranges and doesn't change the UI behavior)

Even with multiple line is it not working
`{/* #region Test */}
<Text>Random Text</Text>
<Text>Random Text 2</Text>
{/* #endregion */}
`

**Comment by daiyam** [comment]
> Is it working but this are not "comment" in typescript

You need to add `"kind": "comment"` to the rule (https://github.com/zokugun/vscode-explicit-folding/blob/master/docs/rules/begin-end.md#kind)

> Even with multiple line is it not working

The `{/*` / `*/}` can be problematic since they can be matched by the TS language provider (as comment blocks) and generate conflicts.

You might try to use `"editor.defaultFoldingRangeProvider": "zokugun.explicit-folding",` but it disable the language provider...

**Comment by mDeSimone-DFactorySrl** [comment]
> > Is it working but this are not "comment" in typescript
> 
> You need to add `"kind": "comment"` to the rule (https://github.com/zokugun/vscode-explicit-folding/blob/master/docs/rules/begin-end.md#kind)
> 
> > Even with multiple line is it not working
> 
> The `{/*` / `*/}` can be problematic since they can be matched by the TS language provider (as comment blocks) and generate conflicts. VSCode gets 2 set of ranges and merge them as it wants.
> 
> You might try to use `"editor.defaultFoldingRangeProvider": "zokugun.explicit-folding",` but it disables the language provider...

unfortunately it is still not working with those settings.

I have managed, thanks to copilot, to make it working adding in settings.json this
```
"explicitFolding.rules": {
        "typescriptreact": {
            "begin": "{/* #region */}",
            "end": "{/* #endregion */}"
        },
        "javascriptreact": {
            "begin": "{/* #region */}",
            "end": "{/* #endregion */}"
        }
    }
```
