### ISSUE TITLE
can I  maintain "editor.foldingStrategy": "indentation"

### ISSUE THREAD

**Issue by nolanjj** [zokugun/vscode-explicit-folding#115]
my setting.json:
  "editor.foldingStrategy": "auto",
  "editor.defaultFoldingRangeProvider": "zokugun.explicit-folding",
  "explicitFolding.rules": {
    "*": [
      {
        "begin": "{{{",
        "end": "}}}"
      },
      {
        "begin": "{",
        "end"  : "}"
      },
      // {
      //   "begin": "(",
      //   "end"  : ")"
      // },
  ]
  },

it work well!,very convenient!!!

but I also want to maintain the feature of "indentation"
so I can 
![image](https://github.com/zokugun/vscode-explicit-folding/assets/35267241/c13acaa5-d570-456a-9b60-0813f60b9e8c)

How to achieve this,thank you.

**Comment by daiyam** [comment]
You have to use the [Indentation rule](https://github.com/zokugun/vscode-explicit-folding/blob/master/docs/rules/indentation.md)

```
"explicitFolding.rules": {
	"*": [
		...
		{
			"indentation": true
		}
	]
}
```

**Comment by nolanjj** [comment]
> You have to use the [Indentation rule](https://github.com/zokugun/vscode-explicit-folding/blob/master/docs/rules/indentation.md)
> 
> ```
> "explicitFolding.rules": {
> 	"*": [
> 		...
> 		{
> 			"indentation": true
> 		}
> 	]
> }
> ```

grateful!!!
