### ISSUE TITLE
Is it possible/how to implement folding with the closing bracket on the same line?

### ISSUE THREAD

**Issue by YakovL** [zokugun/vscode-explicit-folding#12]
There's a long-living [thread](https://github.com/Microsoft/vscode/issues/3352) in the VS Code repo, is vscode-explicit-folding capable of implementing this? If it is, is there a settings snippet to apply and go? If not, can this be implemented, what does this require? Since a number of devs are interested, this may deserve some attention

**Comment by daiyam** [comment]
Hi Yakov, this extension won't fix the referenced issue.
I'm avoiding the issue with a custom build with the PR microsoft/vscode#54200 that I've made. (So the foldings can only be provided only by this extension)

**Comment by daiyam** [comment]
Hi Yakov, I'm not sure if it's useful to you but I've made my custom version of VSCode available at https://github.com/zokugun/MrCode.
Also, for the explicit extension, I've added the `foldLastLine` property to include or not the last line into the folding.

**Comment by hoppfrosch** [comment]
Just to be sure: Using this extension you need to use your customised version of VSCode? Or does your extension work with plain VSCode as well (with restricted features?)?

**Comment by daiyam** [comment]
Hi @hoppfrosch , this extension works with VSCode but the default foldings (provided by `auto` or `indentation`) will always be present. My customized version avoids this if you set the `editor.foldingStrategy` to `explicit`.
