### ISSUE TITLE
Last update does not fold last line

### ISSUE THREAD

**Issue by mjan4175** [zokugun/vscode-explicit-folding#15]
After updating to 0.5, the extension stopped working in PHP code:

My setting is:
```
"folding": {
        "*": [   
            {    
                "beginRegex": "\\{\\{\\{",
                "endRegex": "\\}\\}\\}"
            }
        ]
}
```
Issues:
1. The following does not fold:
```
// This is a PHP comment to be folded {{{
// Oh, what a nice first folded line!   
// Second line to be folded
// }}}
```

2. The following  does not include the last line in fold:
```
public function bbb() { // {{{
    print "aaa";
    print "bbb";
} // }}}
```
 
3.The following folds at second line (non-indented comment to function) and does not include the last line in fold:

```
public function bbb() { // {{{
// comment to function
    print "aaa";
    print "bbb";
} // }}}
```

**Comment by daiyam** [comment]
I'm on it... sorry about that

**Comment by daiyam** [comment]
It's fixed! The published extension was missing the needed dependency...

**Comment by mjan4175** [comment]
Thanks for quick fix, it works now.

**Comment by mjan4175** [comment]
After update to 0.6, the folding is damaged again.

The same issuses as above occur.

**Comment by mjan4175** [comment]
Sorry for reopening the issue. 

After restarting the VS Code all is OK.

Extension works now.

**Comment by daiyam** [comment]
np
