### ISSUE TITLE
cutting a file into blocks

### ISSUE THREAD

**Issue by snuup** [zokugun/vscode-explicit-folding#16]
hi. i would like to fold the file

    111 process xxx      <- begin
    text text 
    text text 
    text text            <- end
    222  process yyy     <- begin
    text text 
    text text 
    text text            <- end
    333  process yyy     <- begin
    text text 
    text text 
    text text            <- end

on the "process" line boundaries. tried with lookahead regex:

    "folding": {
            "log": {
                "beginRegex": "process",            
                "endRegex": "(?=^.*process)"
            }
        },

without success. any hint?

suggestion: for simple break-into-block folding as i intend to do here, it would be nice to allow specifying the begin(Regex) only.

**Comment by daiyam** [comment]
@snuup with the newest version (v0.6.0), you do:

```
"folding": {
    "log": {
        "separator": "process"
    }
}
```

**Comment by daiyam** [comment]
If you have any issue, fell free to reopen this issue.

**Comment by snuup** [comment]
Wow, that is really fast and cool, thank you so much. Check it as soon as its out on market place. Meanwhile read your code ;)

**Comment by daiyam** [comment]
read my code?

**Comment by snuup** [comment]
the changes you just commited.

**Comment by snuup** [comment]
hmm, folding does not occur on my side. i used a file with this content:

    111 process xxx      
    text text 
    text text 
    text text            
    222  process yyy     
    text text 
    text text 
    text text            
    333  process yyy     
    text text 
    text text 
    text text            

and copied exactly your settings.

    "folding": {
        "log": {
            "separator": "process"
        }
    },

 it works on your side?

**Comment by daiyam** [comment]
it does but the file's extension needs to be `log`. You can change the `"log"` to `"*"` to work on all files but you will need to be careful with a generic separator as it is.

**Comment by snuup** [comment]
sure. i closed and reopened vscode, now it works. - the "window reloads" obviously did not have the same effect.

thank you so much @daiyam, that is extremely useful for me now, and i guess for other readers of text log files too ;)

**Comment by retorquere** [comment]
I'm trying to set this up for [Python Interactive](https://code.visualstudio.com/docs/python/jupyter-support-py), but with this

```
"folding": {
      "py": { "separator": "# %%"}
    }
```

I don't see the folding markers for the sections.

**Comment by daiyam** [comment]
try:
```
"folding": {
  "python": { "separator": "# %%"}
}
```

**Comment by retorquere** [comment]
Superb!
