### ISSUE TITLE
Failing to get working config

### ISSUE THREAD

**Issue by kmantel** [zokugun/vscode-explicit-folding#17]
I wanted to use this extension to fold all python docstrings, which doesn't seem to be supported with vscode defaults. I used a config for only python files with `"\"\"\""` for both begin and end, but this failed to add folding arrows as I expected. I tested something simpler to make sure it was formatted correctly, and that seems not to add folding arrows either:

    "folding": {
        "*": {
            "begin": "###",
            "end": "###"
        }
    }

on example .py file

    ###
    pass
    pass
    ###

and no folding arrows are available. Additionally, having any folding config at all seems to disable all folding arrows in several different filetypes (e.g. .py, .sh), but not .json interestingly.

Am I configuring things incorrectly or misinterpreting what can be done with this extension?

**Comment by daiyam** [comment]
@kmantel I've updated the extension to support docstring blocks. Enjoy :smile:

**Comment by kmantel** [comment]
Thanks for the fast response! This works well
