### ISSUE TITLE
No folding for several "begin"s

### ISSUE THREAD

**Issue by Melirius** [zokugun/vscode-explicit-folding#18]
For example, in C/C++ you can have a comment like this:

/* Start of a commented section of code, that can be switched back on just by adding / to the end of this line *
Some code
/* End of the section */ 

Unfortunately extension cannot fold this type of comments.

**Comment by daiyam** [comment]
Hi @Melirius,

In the new version of the extension (v0.7.1), I've added the property `nested` so you can do:

```
{
  "begin": "\/*",
  "end": "*\/",
  "nested": false
}
```

**Comment by Melirius** [comment]
Thank you so much!

**Comment by Melirius** [comment]
Still have a problem with 0.7.1 and _"nested": false_ for the case of

```
/* M23eebr(pApB, pApI, pApJ, pBpI, pBpJ)
/*            p1p2, p1k, p1pp1, p2k, p2pp1 */
```

**Comment by daiyam** [comment]
@Melirius I can't reproduce the issue.
Can you give me your config and an exact example when the foldings aren't correct?

**Comment by Melirius** [comment]
Somehow it was connected to not fully updated extension. It had updated itself again after I reload Code (showing the banner again) and the problem disappeared.
