### ISSUE TITLE
Different methods for one file type

### ISSUE THREAD

**Issue by gmaggio** [zokugun/vscode-explicit-folding#2]
Is it possible to have different methods for one file type?

For example, I would like to be able to fold with the methods below:

```json
"folding": {
    "javascriptreact": {
        "start": "\\{/\\*",
        "end": "\\*/\\}"
    },
    "javascriptreact": {
        "start": "<",
        "end": "/>"
    },
}
```

**Comment by daiyam** [comment]
@gmaggio I've added multiple markers per language.
But I've renamed the extension (to `Explicit Folding`) and renamed `start` to `begin`.
So your configuration should be:
```
"folding": {
    "javascriptreact": [
        {
            "begin": "\\{/\\*",
            "end": "\\*/\\}"
        },
        {
            "begin": "<",
            "end": "/>"
        }
    ]
}
```
