### ISSUE TITLE
`"nested": false` doesn't work in "continuation"-based rules

### ISSUE THREAD

**Issue by HolyBlackCat** [zokugun/vscode-explicit-folding#21]
Now when #20 is fixed, my C++ folding rules are almost done, there's only one problem left.

I assume this was caused by the recent change of how `"nested": false` is handled.

Here's the config:
```json
{
    "begin": "//",
    "continuation": "\\",
    "nested": false,
},
{
    "begin": "{",
    "end": "}",
},
```
And here's the text I test it on:
```
{  folding starts here
123
//  }  folding incorrectly ends here
456
}  folding should end here
```
---
Again, thanks for your great work! I'll send you a link to the C++ rules after I test them a bit.

**Comment by daiyam** [comment]
It's due to how the begin regex is constructed: `\/\/.*\\$`...
