### ISSUE TITLE
Fold automatically

### ISSUE THREAD

**Issue by Shatur95** [zokugun/vscode-explicit-folding#25]
Is there a way to make some make some folds enabled by default? I'd like to fold license in the beginning of the file folded by default.

**Comment by daiyam** [comment]
A folding provider can only provide the list of the folding ranges. I don't think it will be possible with the current extension.

**Comment by Shatur95** [comment]
Got it, thanks. It is strange that there is no extension that automatically folds licenses at the beginning of the file.
