### ISSUE TITLE
Doesn't work in conjunction with indentation foldingStrategy.

### ISSUE THREAD

**Issue by FicoPrieto** [zokugun/vscode-explicit-folding#27]
### Settings

```json
"folding": {
  "*": [
    {
      "begin": "{",
      "end":   "}",
    }
  ]
}
```

&nbsp;  
### Code Example
```javascript
class Foo{
  
  bar(){
    return 1
  }
  
  baz()
    {return 2}
  
}
```

&nbsp;  
### `"editor.foldingStrategy": "auto"`
- `bar` is collapsed by the explicit strategy  
  (*expected*)  
- `baz` is **not** collapsed  
  (*expected, not matched by current strategies*)  

![Code_2020-11-02_12-58-13](https://user-images.githubusercontent.com/22942079/97902127-222aad00-1d0b-11eb-8767-ed1f6d96288e.png)  

&nbsp;  
### `"editor.foldingStrategy": "indentation"`
- `bar` is **not** collapsed by the explicit strategy  
  (*unexpected, this is the titular issue*)  
- `baz` is collapsed by the indentation strategy  
  (*expected*)  

![Code_2020-11-02_12-58-25](https://user-images.githubusercontent.com/22942079/97902128-222aad00-1d0b-11eb-93ca-250eeafb6c14.png)

**Comment by daiyam** [comment]
When `"editor.foldingStrategy": "indentation"`, `vscode` is only using the indentation folding provider. So this extension is never called to provide the folding to the document (or any other folding provider).

This extension and `vscode` don't support folding range on a single line.

**Comment by FicoPrieto** [comment]
@daiyam 

Ok, based on [**README#editors-support**](../#editors-support) it seemed as though this extension would work in conjunction with `editor.foldingStrategy` set to either `auto` or `indentation`.  
&nbsp;  

> VSCode is using the folding ranges provided:
> - by the folding range provider defined by the setting `editor.foldingStrategy` (`auto` or `indentation`)
> - <ins>**and**</ins> by the folding range provider defined by this extension

**Comment by daiyam** [comment]
oops! My bad. It's a mistake, I will have to fix it. sorry.

**Comment by forivall** [comment]
Based on [your comment](https://github.com/zokugun/vscode-explicit-folding/issues/27#issuecomment-720683058), i think that this could be solved by bringing the indentation folding provider inside this extension, so that it can optionally provide indentation-based folding in conjunction with manual folds (i want indentation folding for python + docstring folding by pattern)

**Comment by daiyam** [comment]
@forivall, to do what you propose would be outside the scope of this extension.

But that could be done if `editor.foldingStrategy` supports a list of providers :
- `auto` can become `language | indentation`
- `explicit & indentation` would provide what you looking for

I can implement it in my version of VSCode.

**Comment by daiyam** [comment]
@FicoPrieto For which purpose did you indented to use this extension? To be able to fold the functions `bar()` and `baz()`?

**Comment by FicoPrieto** [comment]
@daiyam 

Yes, I was expecting that both functions would be folded if `foldingStrategy` was set to `indentation` and `vscode-explicit-folding` was configured as shown in the original post.
- `bar` via the explicit strategy
- `baz` via the indentation strategy

**Comment by daiyam** [comment]
@FicoPrieto I've added the support for `"editor.foldingStrategy": "explicit & indentation"` in [MrCode](https://github.com/zokugun/MrCode) (my version of VSCode).
With that, I was able to do exactly what you wanted to do.

**Comment by FicoPrieto** [comment]
@daiyam  
Thanks for implementing it!

It's unfortunate that they haven't accepted your PRs @ `microsoft/vscode`, this would be a great feature to have in VSCode, and I'd definitely prefer to stick with the official distribution.

I've tried a few approaches for re-implementing indentation folding via RegEx, but haven't been successful yet. In theory, this should work - I tested it out in VSCode & RegEx101 and it seems to work pretty well:

- @ [**RegEx101**](https://regex101.com/r/gBzUog/9) (*PCRE w/ comments*)
- @ [**RegEx101**](https://regex101.com/r/laElOH/2) (*ECMAScript*)
- @ **VSCode `Editor.find`**:  
![**VSCode**](https://user-images.githubusercontent.com/22942079/103143961-16e27500-46ef-11eb-8d4b-a0071ebcbdd1.png)

&nbsp;  
&nbsp;  


However, I can't get it to work with `vscode-explicit-folding`. Here is a simpler scenario I tried:

![Code_2020-12-25_20-13-33](https://user-images.githubusercontent.com/22942079/103143923-f4039100-46ed-11eb-9600-d45e6589b02c.png)

```js
/* attempt 1 */ {"beginRegex":"(([\\t ])+)[^\\n]+\\n", "endRegex":"\\1\\2+\\{[^\\n]+\\}"}, 
/* attempt 2 */ {"beginRegex":"(([\\t ])+)[^\\n]+",    "endRegex":"\\1\\2+\\{[^\\n]+\\}"}, 
```

**Comment by daiyam** [comment]
Those expressions won't work because there are multilines expressions which aren't supported by this extension. (It works line by line)

**Comment by daiyam** [comment]
@forivall @FicoPrieto I've changed my mind!
The extension will support the config `{ "indentation": true }`. It should be done in next days.
So many users are already using it way beyond its initial purpose. Why not push it a little bit further ;)

**Comment by FicoPrieto** [comment]
@daiyam Awesome! How did you end up getting it to work? I thought the functionality was being prevented by a limitation of VSCode.

**Comment by daiyam** [comment]
@FicoPrieto Basically, I'm duplicating the builtin indentation provider into this extension. Since I don't like the ideas to duplicate code and to add another provider into the extension. So I thought doing `"editor.foldingStrategy": "explicit & indentation"` was better (still is better). But at the end of the day, there were no "immediate" solutions for user who wanted to stick to VSCode.
Then, yesterday, I had the issue #36 (about jupyter python) and I thought that the extension was kinda useless for python devs. So I decided to give you the choice.

**Comment by daiyam** [comment]
I've made the branch `indentation`.
Here the steps to test it:
- clone the branch
- `npm i` to install the dependencies
- open the directory on VSCode
- hit `F5` to debug the extension.

Or uninstall the extension and install [explicit-folding-0.10.0.vsix](https://github.com/zokugun/vscode-explicit-folding/files/6009491/explicit-folding-0.10.0.vsix.zip) (remove .zip) by dropping the file in the list of extensions.

Here the config, I've used:
```
"python": [
    {
        "beginRegex": "\"\"\"",
        "endRegex": "\"\"\"",
    },
    {
        "separator": "# %%"
    },
    {
        "indentation": true,
        "offSide": true
    }
],
```

@forivall @FicoPrieto @OSHI7 Could you test it?

**Comment by FicoPrieto** [comment]
@daiyam I just tested the code example from the [**first post**](#issue-734715402) with the following settings:

```json
"editor.foldingStrategy": "auto",

"folding": {
  "*": [
    {
      "begin": "{",
      "end":   "}",
    },
    {
      "indentation": true,
      "offSide":     true,
    },
  ]
}
```

## Result

![image](https://user-images.githubusercontent.com/22942079/108527500-587f3e80-72a0-11eb-9b69-7af839d8b3d9.png)

- `bar` is partially collapsed  
  (*expected line 5 to be collapsed into line 3, as when omitting the {`indentation`, `offSide`} group*)

- `baz` is collapsed  
  (*as expected*)

**Comment by daiyam** [comment]
@FicoPrieto yep, I need to make the indentation loop to play well with the regex loop...

**Comment by daiyam** [comment]
@FicoPrieto I've made some small changes [explicit-folding-0.10.0.vsix.zip](https://github.com/zokugun/vscode-explicit-folding/files/6011475/explicit-folding-0.10.0.vsix.zip)

**Comment by FicoPrieto** [comment]
@daiyam Seems to be working as expected, thanks for implementing this!!

**Comment by OSHI7** [comment]
I'd try to test this, but am learning here as i go. Can i install this .vsix on vsCode? Not sure what's up and how to do this yet. I'll try to figure it out, sounds awesome.

**Comment by daiyam** [comment]
I've published the new version of the extension.

@OSHI7 You can try with the config:
```
"folding": {
	"python": [
		{
			"separatorRegex": "#\\s*%%"
		},
		{
			"indentation": true,
			"offSide": true
		}
	]
}
```

**Comment by OSHI7** [comment]
@daiyam, I see!  
Yes, I think it works well. I will continue to test and follow up soon.
Q: I note there is a small blue rectangle, as on line 24..It appears on all `#%%` sections - they fold well, and the same as the `if` and `while`, but I note the special blue rectangle in the gutter.  I am assuming this is by design? 

![image](https://user-images.githubusercontent.com/23404030/108582009-990da500-72fe-11eb-92af-b31eca480537.png)
