### ISSUE TITLE
first time user confused, sorry!

### ISSUE THREAD

**Issue by op12no2** [zokugun/vscode-explicit-folding#28]
Hi,

We have a huge code repo folded with !{{{ and }}} for various file extensions . For the last 20 years we have used a custom written editor. In trying to enter the 21st century we are trying vsCode. I installed your extension, which seems exactly what we require but cannot get it to work.

my settings code looks like this:-

```
{
   "folding": {
      "*": {
        "begin": "!{{{",
        "end": "!}}}"
      }
   }
}
```

But when I open a file folded like that, it does not show folded.  This is vsCode newly installed today.  I'm probably doing something silly and pointers would be appreciated.  Thanks.

**Comment by op12no2** [comment]
Hi,

Closing marker is !}}}

File contain Clarion code.  File extension is .clw. ! is the comment character.

**Comment by op12no2** [comment]
Example - but would have a .clw extension. Github did not allow upload of .clw.

[as_stuff.txt](https://github.com/zokugun/vscode-explicit-folding/files/5679905/as_stuff.txt)

**Comment by daiyam** [comment]
So you are using the [emacs foldings](https://www.emacswiki.org/emacs/FoldingMode) which is my main purpose for writing this extension...

My config:
```
{
  "editor.foldingStrategy": "auto",
  "folding": {
    "*": {
      "begin": "{{{",
      "end": "}}}"
    }
  }
}
```

Here what I got:
![Screen Shot 2020-12-11 at 4 15 26 PM](https://user-images.githubusercontent.com/587742/101920590-49a74c00-3bcc-11eb-8246-66909c50d0a6.png)

**Comment by op12no2** [comment]
![Capture](https://user-images.githubusercontent.com/9113269/101922329-ddc1e500-3bc5-11eb-96d9-624902463e65.PNG)
![Capture2](https://user-images.githubusercontent.com/9113269/101922332-de5a7b80-3bc5-11eb-8380-d94c771f4972.PNG)

OK thanks. I must be doing something wrong, or missing something obvious :)  I'll keep fiddling.

**Comment by daiyam** [comment]
Ya, something isn't right. I had it working but then it doesn't... I will have to debug to understand why.
![Screen Shot 2020-12-11 at 4 47 01 PM](https://user-images.githubusercontent.com/587742/101925921-bfaeb180-3bd2-11eb-96d3-5ac743b5cda0.png)

In the meantimes, you could try with [MrCode](https://github.com/zokugun/MrCode)

**Comment by daiyam** [comment]
@op12no2 I've the issue... here the working config:
```
{
	"editor.showFoldingControls": "always",
	"folding": {
		"*": {
			"begin": "{{{",
			"end": "}}}"
		},
	},
}
```

**Comment by op12no2** [comment]
That's very helpful thanks. It's recognising the folds now but starting with them all open.  Do you know a way to start with them all closed on file open?  Sorry to be a pain!

**Comment by daiyam** [comment]
Glad that's working. No I don't but I use the shortcut `editor.foldAll` (when: editorTextFocus).

**Comment by op12no2** [comment]
Thanks. crtl+k+0 by default does it.  I'll figure out how to do that on file open.  Thanks very much for your help. If you are ever in Swansea I'll buy you endless drinks :)
