### ISSUE TITLE
Is it possible to fold inline classes?

### ISSUE THREAD

**Issue by utopianknight** [zokugun/vscode-explicit-folding#29]
I'd like to do this:

![autofoldclasses](https://user-images.githubusercontent.com/25604837/101728151-c98ac480-3aad-11eb-9790-abc8e61b11de.gif)

I have the following in my settings.json but it doesn't work.

````javascript
"folding": {
    "html": {
        "begin": "class=\"",
        "end": "\""
    },
    "vue": {
        "begin": "class=\"",
        "end": "\""
    }
}
````

**Comment by daiyam** [comment]
@utopianknight Single-line foldings aren't supported by Visual Studio Code and so by this extension.

**Comment by utopianknight** [comment]
I can fold this:

```html
<div class="
    my-custom-class
"></div>
```

So can't we have something that also works like an auto-formatter?

**Comment by daiyam** [comment]
@utopianknight This extension is event aware of the syntax of a language, it's just text. For VSCode, a folding needs to be multi-lines.
