### ISSUE TITLE
Not sure how to use...

### ISSUE THREAD

**Issue by robertcatgithub** [zokugun/vscode-explicit-folding#3]
hi can you please help ? I'm new to VS Code.  The code of the script I want to fold is very OLD, obscure VB-like language. (PICK). The comment character is "*".

Can you let me know how to use your extension ?
thanks

**Comment by daiyam** [comment]
Hi Robert,

Pick/Basic doesn't seem to have comment blocks so your best option is to use emacs folding (`{{{` and `}}}`).
For example:
```
* {{{
PRINT "ENTER NAME"
INPUT NAME
IF NAME = "" THEN STOP
* }}}
```

Here the settings for that:
```
"folding": {
    "*": {
        "begin": "\\{\\{\\{",
        "end": "\\}\\}\\}"
    }
}
```

**Comment by daiyam** [comment]
Hi @louie6111,

The extension read the code line by line so it won't see the `\n`.

How do you close the last section by only using `\section`? 

In Latex, you could use something like:
```
\begin{document}
 
\chapter{Let's begin}
 
\section{First Attempt} % {{{
 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut 
enim ad minim veniam, quis nostrud exercitation ullamco laboris...
% }}}
 
\section{Second attempt} % {{{
 
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut 
enim ad minim veniam, quis nostrud exercitation ullamco laboris...
% }}}
 
\end{document}
```
