### ISSUE TITLE
Cannot get nested HTML folding to work within a data script element

### ISSUE THREAD

**Issue by TotallyInformation** [zokugun/vscode-explicit-folding#33]
## Describe the bug

When editing HTML using VScode's `auto` folding. Nested html elements do not seem to fold when they are inside a `<script>` element. I've already used this extension to add JSDoc folding to javascript files but I cannot find a setting that lets me fold nested html elements inside the script element.

![image](https://user-images.githubusercontent.com/1591850/107881458-57cf5c80-6edc-11eb-9b25-e4d94094bf4a.png)

Note how folding works OK for the nested para elements but not inside script.

## To reproduce

- VSCode: 1.53.2
- Language: html
- Language Provider: Built-in?

### Code Example

```
<script type="text/html" data-help-name="uibuilder">
    <p>Easily create a data-driven web user interface (UI)</p>
    <p>
        Create dynamic, data-driven user interfaces that send and receive messages to/from Node-RED.
        Creates a file/folder structure that is used to deliver static resources (html, css, js, images, etc) and
        manages the delivery of vendor library resources (VueJS, jQuery, etc).
        You can also pass script and style information to the front-end in a message.
    </p>
</script>
```

### Settings

```
"folding": {
  "html": {
    "begin": "<",
    "end": "</",
  }
}
```

OR

```
"folding": {
  "html": {
    "beginRegex": "\\<.*\\>",
    "endRegex": "\\</.*\\>"
  }
}
```

Note, however, that the following **DOES** work, but obviously only for the para element, not for anything else:

```
"folding": {
  "html": {
    "begin": "<p",
    "end": "</p",
  }
}
```

## Expected behavior

Folding should occur within an outer `<script>` element

## Screenshots

See above

## Additional context

If you were able to add an `indent` option so that we could turn on indentation folding as well as specific folding, that would also fix this and other issues.

Reference to the issue I've raised in VScode as well that relates to this issue: https://github.com/microsoft/vscode/issues/116652

**Comment by daiyam** [comment]
The following config should be working:

```
"folding": {
    "html": {
        "beginRegex": "<([a-zA-Z]+)",
        "endRegex": "<\\/\\1>",
    },
}
```

**Comment by TotallyInformation** [comment]
Hi, thanks for the quick reply. 

No, that doesn't work either.

**Comment by daiyam** [comment]
Here what I get:
![Screenshot](https://user-images.githubusercontent.com/587742/107883768-3167ec00-6ef1-11eb-8aa5-c726152d717e.png)

What do you have?

**Comment by TotallyInformation** [comment]
![image](https://user-images.githubusercontent.com/1591850/107883814-1c875a80-6ee9-11eb-9910-82becab4e145.png)

Urm, odd - I got a single fold there. 2 others lower down as well. Seems random.

**Comment by daiyam** [comment]
It was due to `<input` which doesn't have a closing tag...

The following config is giving me:
```
"folding": {
    "html": {
        "beginRegex": "<(?!area|base|br|col|embed|hr|img|input|link|menuitem|meta|param|source|track|wbr)([a-zA-Z]+)[^>\\/]*>",
        "endRegex": "<\\/\\1>"
    },
}
```

![Screenshot](https://user-images.githubusercontent.com/587742/107884682-a8ec4a00-6ef6-11eb-9dc9-16aede14e126.png)

`(?!area|base|br|col|embed|hr|img|input|link|menuitem|meta|param|source|track|wbr)` is excluding void html tags so they won't be match as opening tags.
`[^>\\/]*>` is excluding self-closed tags.

**Comment by TotallyInformation** [comment]
Fantastic - many thanks for that. Great job.
