### ISSUE TITLE
PHP switch case fallthrough folding goes away for self and parents

### ISSUE THREAD

**Issue by inventor96** [zokugun/vscode-explicit-folding#34]
## Describe the issue
When I have a switch case in PHP that include fallthrough cases (two cases that go to the same set of actions), the folding of all parent folds go away.

## To reproduce
- VSCode: 1.53.2
- Explicit Folding: 0.9.2
- Language: php
- Language Provider: PHP Intelephense (bmewburn.vscode-intelephense-client)

### Code Example
```
<?php

function methodOne($var) {
	switch ($var) {
		case 'hi':
		case 'hi2':
			echo 'hi';
			break;
		case 'hello2':
			echo 'something else';
		case 'hello':
			echo 'hello';
			break;
		default:
			echo 'nothing';
			break;
	}
}

function methodTwo($var) {
	switch ($var) {
		case 'bye':
			echo 'bye';
			break;
		case 'see ya':
			echo 'see ya';
			break;
		default:
			echo 'nothing again';
			break;
	}
}
```

### Settings
```
"folding": {
	"php": [
		{
			//"begin": "case",
			//"end": "break;",

			"beginRegex": "(?:case|default)[^:]*:",
			"middleRegex": "(?:case|default)[^:]*:",

			//"beginRegex": "(?:[\\r\\n\\s]*?(?:case|default)[^:]*:){1,}",
			//"middleRegex": "(?:[\\r\\n\\s]*?(?:case|default)[^:]*:){1,}",

			"endRegex": "break;",

			//"kind": "comment",
			//"nested": false
		},
		/* {
			"begin": "default",
			"end": "break;"
		}, */
		{
			"beginRegex": "{",
			"middleRegex": "}[^}]+{",
			"endRegex": "}"
		},
		{
			"begin": "/*",
			"end": "*/"
		},
		{
			"begin": "\"",
			"end": "\""
		},
		{
			"begin": "'",
			"end": "'"
		},
		{
			"begin": "[",
			"end": "]"
		},
		{
			"begin": "(",
			"end": ")"
		}
	]
}
```

## Expected behavior
The code should fold at the last case statement in the group for direct fallthrough setups (e.g. `case 'hi2':` in my example). The code should fold at both case statements when there's a fallthrough with other actions (e.g. `case 'hello2':` and `case 'hello':` in my example). In both cases, the parent folds should still be available.

## Screenshots
In this screenshot, I would expect to see folds for lines 3, 4, and 9.
![image](https://user-images.githubusercontent.com/7132744/107995577-c0314300-6f9b-11eb-9a21-863e8c0ca187.png)

## Additional context
I've tried many variations for the `begin(Regex)`, `middle(Regex)` keys, as well as played around with `nested` and `kind`, but I have yet to achieve the desired results. You can see some of my attempts in the commented portions of my folding settings. The settings included here are what were set at the time I took the screenshot.

**Comment by daiyam** [comment]
Me too, I can't figure out how to do what you want... 😞

**Comment by daiyam** [comment]
Maybe something like this (it's a work in progress):

```
{
    "beginRegex": "(?:case|default)[^:]*:",
    "endRegex": "break;|(.)(?=case|default|\\})",
    "foldLastLine": [true, false]
}
```

which give me
![Screenshot](https://user-images.githubusercontent.com/587742/108008541-dfae8700-7000-11eb-914b-5d35414a11bb.png)

`foldLastLine` is modified so that `"foldLastLine": [true, false]`:
- `true`: by default
- `false`: if the end's group with the index `1` has a value

What do you think?

**Comment by inventor96** [comment]
That sounds good to me. Is it easy for me to try out your code changes so I can see how it works with real code instead of only test stuff?

**Comment by daiyam** [comment]
I've made the branch `fold-switch`.
Here the steps to test it:
- clone the branch
- `npm i` to install the dependencies
- open the directory on VSCode
- hit `F5` to debug the extension.

Or uninstall the extension and install [explicit-folding-0.9.2.vsix](https://github.com/zokugun/vscode-explicit-folding/files/5985941/explicit-folding-0.9.2.vsix.zip) (remove `.zip`) by dropping the file in the list of extensions.

**Comment by inventor96** [comment]
I used the later method for simplicity. Everything looks good in the more complex files I was working in today that had switch statements.

**Comment by daiyam** [comment]
@inventor96 I've published a new version of the extension with the changes you have tested.

**Comment by inventor96** [comment]
Sounds good. I'll close this for now since the original issue has been fixed. Thanks for your work!
