### ISSUE TITLE
Brackets in a string are also folded

### ISSUE THREAD

**Issue by hdcontrino** [zokugun/vscode-explicit-folding#38]
## Describe the issue
I have this problem in PHP, in other languages I have not tried it. 
I tried to deny them in settings.json but no effect. 
when I have brackets in strings the logic of the folding breaks.

## To reproduce

- VSCode: 1.54.3
- Explicit Folding: 0.11.0
- Language: Spanish
- Language Provider: Spanish Language Pack for Visual Studio Code v1.54.2

### Code Example
```
$foo = '{any string';
$bar = 'another string';
$qux = 'last string }';
```

### Settings
```
"folding": {
    "php": {
        "begin": "{",
        "end": "}"
    }
}
```

## Expected behavior

The expected behavior should be nothing.

## Screenshots

![gif](https://user-images.githubusercontent.com/80926805/111788763-34af1880-889f-11eb-81b8-4a0a4e643ad2.gif)

## Additional context

I tried to add a negation in this way: `"beginRegex": "(?<!')\\{";`
... and many other ways, but all end up disabling the folding.

**Comment by hdcontrino** [comment]
I have solved the issue by editing my regex.
It also solves another issue that I did not describe here, which are the strings with brackets inside brackets.
```
"folding": {
    "php": {
        "beginRegex": "[^'\"]\\{",
        "endRegex": "\\}(?!['\"])"
    }
}
``
I still need to solve the folding in Heredoc and Howdoc. Any suggestion?

**Comment by daiyam** [comment]
@hdcontrino In Heredoc, you can set `"nested": false`, it will avoid any foldings inside the comment.

**Comment by hdcontrino** [comment]
> @hdcontrino In Heredoc, you can set `"nested": false`, it will avoid any foldings inside the comment.

Nice! Thanks
