### ISSUE TITLE
Add a debug mode with feeding a log

### ISSUE THREAD

**Issue by FALLAI-Denis** [zokugun/vscode-explicit-folding#42]
Hi,

Fine-tuning the folding conditions can be tricky, especially with regular expressions.

It would be necessary to be able to have a debug mode in the extension, with feeding of a specific log output: the results of regular expression tests (since the extension transforms everything into regular expressions), would be displayed in this log.
To be able to find to which case of folding corresponds which regular expression test, it would be necessary to be able to name each case of folding.

Either something like:

```
"folding": {
     "debug": true,
     "language": [
      {"name": "name_of_folding_case_ # 1"
      , "beginRegex": "start_expression_ # 1"
      , "endRegex": "end_expression_ # 1"
      }
      ,
      {"name": "name_of_folding_case_ # 2"
      , "beginRegex": "start_expression_ # 2"
      , "endRegex": "end_expression_ # 2"
      }
   ]
}
```

For the content of the log, see for example what the site https://regex101.com/ displays as information on the results of a regular expression in its "match information" window.

Thanks.

**Comment by daiyam** [comment]
Ya, it's being in my todo list since the beginning of the year...

**Comment by FALLAI-Denis** [comment]
Solved.
