### ISSUE TITLE
When beginRegex and endRegex are the same only a portion of blocks are foldable 

### ISSUE THREAD

**Issue by h1psta** [zokugun/vscode-explicit-folding#43]
Example: Interactive Python in VSCode uses #%% to denote cells. I want to collapse the individual cells without needing to 
define a character sequence denoting its end. 

I tried :
"python": {
            "beginRegex": "#%%",
            "endRegex": "#%%",
            "foldLastLine": false }

What happens: 
Certain cells are uncollapsible (it looked like it's every other one but not quite)

**Comment by daiyam** [comment]
For code cells, you should use:
```
"python": [
  {
    "separatorRegex": "#\\s*%%"
  },
],
```

**Comment by h1psta** [comment]
Thanks :) !
