### ISSUE TITLE
Folding not working after updating config

### ISSUE THREAD

**Issue by zacksmash** [zokugun/vscode-explicit-folding#49]
## Describe the issue
Not able to get folding keyboard shortcut to execute. Folding in general doesn't seem to be working with new configuration.

## To reproduce
- VSCode: 1.57.1
- Explicit Folding: 0.14.1
- Language: scss
- Language Provider:  N/A

### Code Example

```scss
//|>   Block

//$variable: #fff;

//<|
```

### Settings
```json
"explicitFolding.rules": {
    "scss": [
      {
        "begin": "|>",
        "end": "<|"
      },
      {
        "begin": "region",
        "end": "endregion"
      }
    ]
  },
```

## Expected behavior
Items between the specified begin and end params should fold, either with the gutter controls or with the keyboard shortcut.

**Comment by HolyBlackCat** [comment]
I have this problem too. `"folding"` works, but the suggested `"explicitFolding.rules"` doesn't.

**Comment by daiyam** [comment]
I'm sorry! I've just published an update fixing the issue. It should be available in 5 minutes in the store.

**Comment by daiyam** [comment]
I've been able to update it from the store. The issue is fixed. Sorry again.

**Comment by zacksmash** [comment]
@daiyam This works great after updating! Definitely the quickest issue-to-fix I've ever experienced. haha Thanks!
