### ISSUE TITLE
Broken since last update

### ISSUE THREAD

**Issue by vincent456** [zokugun/vscode-explicit-folding#5]
I'm using Visual Studio Code version 1.29.0 and the addon seems to be broken. It used to work very well before. Can anyone confirm or infirm that the addon has broken ?

**Comment by daiyam** [comment]
@vincent456 I'm looking at it :sob:

**Comment by daiyam** [comment]
@vincent456 No issue here (on Javascript files). Can you tell me your configuration and the type of files you are using?

**Comment by vincent456** [comment]
My versions are : VSCode version 1.29.0
commit 5f24c93878bd4bc645a4a17c620e2487b11005f9
electron 2.0.12
chrome 61.0.3163.100
NodeJS:8.9.3
V8 : 6.1.534.41
architecture x64
latest ubuntu 18.10, everything updated

my settings are 
{
    "cmake.configureOnOpen": true,
    "terminal.integrated.rendererType": "dom",
    "editor.multiCursorModifier": "ctrlCmd",
    "folding": {
        "*": [{
            "begin": "/*",
            "end": "*/"
        },
        {
            "begin":"//region",
            "end":"//endregion"
        }
        ]
    }
}

and I try to appy the custom folds on C++ files (.h,.cc, etc)

**Comment by vincent456** [comment]
Is there a way to debug these kinds of problems ?

**Comment by vincent456** [comment]
I got news : the folding region I'm trying to do with the "/*" and "*/" yeild "syntax error : invalid regular expression "/*//" nothing to repeat"

**Comment by daiyam** [comment]
Ok, the markers are RegExp. So it should be:
```
"folding": {
        "*": [{
            "begin": "\\/\\*",
            "end": "\\*\\/"
        },
        {
            "begin":"\\/\\/region",
            "end":"\\/\\/endregion"
        }
        ]
    }
```

But I have an issue with c++ files. I will try to look into it this week-end.
I have to look into VCS and understand what have been changed since my extension hasn't changed...

I have a [PR](https://github.com/Microsoft/vscode/pull/54200) in VCS to allow more flexibility more but right now, it's a dud!

**Comment by vincent456** [comment]
it's fixed : the extension is using regular expressions, so in order to do "/*" I had to do "\/\*" instead

**Comment by daiyam** [comment]
Great! I will update the README to clearly indicate that it's using RegExp.

**Comment by vincent456** [comment]
thank you for the help
