### ISSUE TITLE
Extension hangs when using "nested": false together with "foldLastLine": false

### ISSUE THREAD

**Issue by HolyBlackCat** [zokugun/vscode-explicit-folding#50]
## Describe the issue
The extension hangs, and I can't type anything unti I reload the window.

## To reproduce

- VSCode: 1.57.0
- Explicit Folding: 0.14.2
- Language: `cpp`

### Code Example
```
XY
```

### Settings
```json
    "folding": {
        "cpp": [
            {
                "beginRegex": "X",
                "endRegex": "Y",
                "nested": false,
                "foldLastLine": false,
            },
        ],
    },
```

## Expected behavior
No hanging.

## Additional context
This used to work in previous versions.

**Comment by daiyam** [comment]
Please check if it's ok with the version 0.14.3. Thx
