### ISSUE TITLE
`"nested": false` misbehaves when the 'end' marker is on the same line as other folding markers

### ISSUE THREAD

**Issue by HolyBlackCat** [zokugun/vscode-explicit-folding#53]
## Describe the issue
Folding ranges are determined incorrectly. It seems to happen when the end of a `"nested": false` has other folding markers on the same line.

`"consumeEnd": false` doesn't help much. It causes the extension to hang in some cases, and even when it works, it forces `"foldLastLine": false`, which I don't want.

## To reproduce
- VSCode: 1.57.1
- Explicit Folding: 0.14.6
- Language: `cpp`

### Code Example

1. 	```
	(
	    
	/*

	*/)
	```

2. 	```
	(
	    
	(/**/)

	)
	```

### Settings
```json
    "explicitFolding.rules": {
        "cpp": [
            {
                "begin": "/*",
                "end": "*/",
                "nested": false,
                // "consumeEnd": false,
            },
            {
                "begin": "(",
                "end": ")",
                "foldLastLine": false,
            },
        ],
    },
```

## Expected behavior
For the first example, I expected to be able to fold it like this: (in addition to being able to fold `/* */`, which does work)
```
▶ (
  */)
```
Hovever this folding range is not registered. Only `/* */` is. It starts working if I remove `"nested": false`.

For the second example, I expected to be able to fold it like this:
```
▶ (
  )
```
But instead it folds like this:
```
  (

▶ (/**/)
  )
```
This too starts working if I remove `"nested": false`.

---

If you uncomment `// "consumeEnd": false,`, then:
* The first example sort of works, but it behaves as if `"foldLastLine": false` was set for `/* */`, which I don't want.
* The second example hangs the extension.

## Additional context
I think those rules did work for me in older versions.

**Comment by daiyam** [comment]
@HolyBlackCat https://github.com/zokugun/vscode-explicit-folding/commit/4b7a1d7a8fe3cb8ecd0720c147b80ad6eb2c2566 is fixing both examples and the hanging issue. The new updated extension should be available soon (already published).
I've added your examples in the test units. Sorry about those regressions.

**Comment by HolyBlackCat** [comment]
@daiyam Thanks for the quick reply & fix! 

I found a related problem: if you add `"foldLastLine": false` to the first rule, then following snippets stop folding properly:
* ```
    (
        
    /*
    
    */)
    ```
    
* ```
    (
        
    (/*
        
    */)
        
    )
    ```

**Comment by daiyam** [comment]
`v0.14.8` is on its way. It's good to have more test cases.

**Comment by HolyBlackCat** [comment]
Thanks again!
