### ISSUE TITLE
Python fold on indent and symbol at the same time

### ISSUE THREAD

**Issue by tothedistance** [zokugun/vscode-explicit-folding#69]
## Describe the issue
I need to fold to () when calling functions with lots of parameters.
but on the other hand, I need to fold according to indentation.

## To reproduce

- VSCode: 1.60.1
- Explicit Folding:  0.19.2
- Language:  python
- Language Provider: python

### Code Example
```
def func(
    var 1,
    var 2,
):
    some code
    more code
    fold to here

result = func(
    var 1,
    var 2,
)
```

### Settings
```
"folding": {
  "*": {
    "begin": "(",
    "end": ")",
  }
}
```

**Comment by daiyam** [comment]
For Python, you can try:

```
"[python]": {
  "explicitFolding.rules": [
    {
      "beginRegex": "\"\"\"",
      "endRegex": "\"\"\"",
    },
    {
      "separatorRegex": "#\\s*%%"
    },
    {
      "begin": "(",
      "end": ")",
    },
    {
      "indentation": true,
      "offSide": true
    }
  ]
},
```

**Comment by daiyam** [comment]
@tothedistance Were you able to try the settings?

**Comment by ymoslem** [comment]
This works well. Thanks! I even added this to fold on commented blocks.
```
    {
      "separatorRegex": "#\\s*"
    },
```

**Comment by tothedistance** [comment]
> For Python, you can try:
> 
> ```
> "[python]": {
>   "explicitFolding.rules": [
>     {
>       "beginRegex": "\"\"\"",
>       "endRegex": "\"\"\"",
>     },
>     {
>       "separatorRegex": "#\\s*%%"
>     },
>     {
>       "begin": "(",
>       "end": ")",
>     },
>     {
>       "indentation": true,
>       "offSide": true
>     }
>   ]
> },
> ```

works great. didn't know why the email notification come to me so late
