### ISSUE TITLE
Custom folding in Vue files.

### ISSUE THREAD

**Issue by oxk4r01** [zokugun/vscode-explicit-folding#70]
Hi. I'm triying to fold custom regions in vue files, and have this setup:
```
"explicitFolding.wilcardExclusions": [
    "vue"
  ],
  "explicitFolding.rules": {
    "*": {
      "begin": "//b/",
      "end": "//e/"
    }
  }
```
And then in the editor:
```
<script>
//b/
import HelloWorld from '@/components/00HelloWorld.vue'
//e/
...
```
But I'm not getting the supposed folding icon. Can you help me with this, please? 
(I'm using Vetur).
Regards.

**Comment by daiyam** [comment]
try:
```
"[vue]": {
  "explicitFolding.rules": [
    {
      "begin": "//b/",
      "end": "//e/",
    },
  ]
},
```

**Comment by oxk4r01** [comment]
There was another [vue] entry in the json, and I had to put that inside it to avoid duplicates.
I did it like that, but doesn't work :(

![image](https://user-images.githubusercontent.com/1032224/133933234-e0dc3c65-f43a-4176-ac28-656efe0f178b.png)
![image](https://user-images.githubusercontent.com/1032224/133933236-1692f67f-e2d5-4428-a527-974f5b3a7d45.png)

**Comment by daiyam** [comment]
You can test 3 things:
- check if the Langage Mode is `Vue` (on the bottom right of the editor)
- check if you have the setting `"editor.showFoldingControls": "always"`
- add the setting `"explicitFolding.debug": true` inside `[vue]` and paste the logs here

**Comment by oxk4r01** [comment]
"Show folding controls" was already set up to "always".

![image](https://user-images.githubusercontent.com/1032224/133936061-53ba08bb-c523-4bde-8903-4a8900bc0f72.png)

But I'm not getting any Folding channel:
![image](https://user-images.githubusercontent.com/1032224/133936067-fca5acc2-78ec-485e-86f3-b23382c5b4b8.png)

**Comment by oxk4r01** [comment]
Hey, I find it. This was the problem:

![image](https://user-images.githubusercontent.com/1032224/133936405-cbf723a8-d982-4aff-81b7-ad5e0d1f7aaa.png)

If "folding strategy" is setup to "indentation", the extension doesn't work. When it's in "auto", the extension panel shows up in the output and the extension works.

**Comment by daiyam** [comment]
Ok, good! I didn't think of that.

**Comment by daiyam** [comment]
I'm closing the issue since it has been fixed :wink:
