### ISSUE TITLE
FR: add attributes for web extension

### ISSUE THREAD

**Issue by GitMensch** [zokugun/vscode-explicit-folding#71]
Currently this extension is not "compatible", it may be enough to add the web entry point, see https://code.visualstudio.com/docs/editor/vscode-web#_extensions for more details.

**Comment by daiyam** [comment]
Since the newest version, the extension is compatible.

**Comment by GitMensch** [comment]
Cool! Do you mind to update the "sister" extension https://github.com/zokugun/vscode-cobol-folding, too?

**Comment by GitMensch** [comment]
That extension was also updated, looks I was too late for my PR there ;-)
