### ISSUE TITLE
Fold className attribute in .jsx files

### ISSUE THREAD

**Issue by maplesyrupman** [zokugun/vscode-explicit-folding#72]
## Describe the issue

Trying to achieve folding of className attribute in .jsx files for react. I am using tailwind so my classNames get quite verbose.

### Code Example
hoping to convert this:
```
   <div className='some-superlong list-of-tailwind utility-classes that clutter-up this-file'>
      <p className='some-more utility-classes that-need to get-folded'>
   </div>
```
into this:
```
   <div className='...'>
      <p className='...'>
   </div>
```

I also asked this question on [stackoverflow](https://stackoverflow.com/questions/70626179/customize-code-folding-for-js-and-jsx-files-in-vscode-to-achieve-folding-of-cl) 

Any help would be greatly appreciated. I also feel like this would be an extremely useful extension, but am unsure as to how I would go about creating this.

**Comment by daiyam** [comment]
I'm sorry but vscode can't do that. It's folding a blocks of lines, not a block of characters like you want.
This extension is providing another way to define the folding ranges. It doesn't change how there are displayed.
