### ISSUE TITLE
F.A.Q. section in `README.md` is unclear about multi-line `regex`

### ISSUE THREAD

**Issue by OCRenkist** [zokugun/vscode-explicit-folding#74]
The suggested answer regarding why `\n` does not work, mentions that `$` must be used, but provides no example of how to do that using the Mozilla `regex` syntax. Likewise, Mozilla-provided documentation is unclear to me regarding this use case.

**Comment by daiyam** [comment]
Since `The document parser is line-based.`, multi-lines regexes won't work.

I know you are trying to fold `Lua` but can you give me an example of what you want to fold (function, if, for, comment or ???)

You can look at [the discussions](https://github.com/zokugun/vscode-explicit-folding/discussions/categories/show-and-tell) to see how some users have successfully used the extension.

**Comment by OCRenkist** [comment]
# Examples for Lua
I have prepared these code-folding examples at your request. 😊 
(And much gratitude for how you are matching my style of `keyword` highlighting.)

💡 **Main idea:** When folded, I want to hide the `end` statements as well as the contents of the blocks the end.
## Single-Level Blocks
The simple case is a single, top-level block with an `end` statement.
### The block:
> ➖ **if** conditions **then**  
&emsp;&emsp; actions  
&emsp; **end**

### Should fold to:
> ➕ **if** conditions **then**

## Multi-Level Blocks
Blocks with other blocks defined as nested within them must allow the nested blocks to be folded without having to fold the parent block(s).
### The blocks:
> ➖ **for** conditions **do**  
➖&emsp; **if** stack:get_name() == "" **then**  
&emsp;&emsp;&emsp; actions  
➖&emsp; **else**  
&emsp;&emsp;&emsp; actions  
&emsp;&emsp; **end**  
&emsp; **end**

### Sould fold to:
> ➖ **for** conditions **do**  
➖&emsp; **if** conditions **then**  
&emsp;&emsp;&emsp; actions  
➕&emsp; **else**  
&emsp;&emsp; **end**  
&emsp; **end**  

⚠️ **NOTICE:** A nested block which is folded _should not_ hide the `end` statement for its parent block, even if the nested block has no `end` statement of its own according to `Lua` syntax.

### And then to:
> ➖ **for** conditions **do**  
➕&emsp; **if** conditions **then**  
&emsp; **end**

### And finaly:
> ➕ **for** conditions **do**


## Blocks Defined on Multiple Lines

When dealing with blocks where the opening statements span multiple lines, place the folding toggle on the first line.

### The block:
> ➖ **if** conditions  
&emsp; **then**  
&emsp;&emsp; actions  
&emsp; **end**

### Should fold to:
> ➕ **if** conditions  

💡 Or consider the typical case from `C`-like languages:
### The block:
> public static void main()  
{  
&emsp; continue;  
}

### Should not appear as:
> &emsp; public static void main()  
➖ {  
&emsp;&emsp; continue;  
&emsp; }

### But rather:
> ➖ public static void main()  
&emsp; {  
&emsp;&emsp; continue;  
&emsp; }

**Comment by daiyam** [comment]
I will use `https://github.com/lcpz/lain/blob/master/layout/termfair.lua` as my test file since it contains most of the cases.

**Comment by daiyam** [comment]
For `Lua`, here the config that I used:
```
"[lua]": {
  "explicitFolding.debug": true,
  "explicitFolding.rules": [
    {
      "begin": "--[[",
      "end": "--]]",
      "nested": false,
      "kind": "comment",
    },
    {
      "begin": "--",
      "continuation": "\\",
      "nested": false,
      "kind": "comment",
    },
    {
      "begin": "\"",
      "end": "\"",
      "nested": false,
    },
    {
      "beginRegex": "\\b(?:for|function|if)\\b",
      "middleRegex": "\\belse(?:if)?\\b",
      "endRegex": "\\bend\\b",
    },
  ],
},
```

For `C`, you should look at https://github.com/zokugun/vscode-explicit-folding/discussions/44

**Comment by daiyam** [comment]
Were the configs helpful?
