### ISSUE TITLE
remember collapsed regions

### ISSUE THREAD

**Issue by daiyam** [zokugun/vscode-explicit-folding#78]
When I change the option in folding strategy from auto to indentation and reopen vscode, it does remember which functions were folded and which weren't.
However, this type of folding is very weird as it folds empty lines and things outside brackets :/

 
![image](https://user-images.githubusercontent.com/103058225/161835172-d82abd6f-45d5-4f7f-aba2-d8c405169907.png)

_Originally posted by @R3uan3 in https://github.com/zokugun/vscode-explicit-folding/issues/64#issuecomment-1089241520_

**Comment by daiyam** [comment]
@R3uan3 I've opened a new issue for the one you have raised.

**Comment by R3uan3** [comment]
Thank you! Im following it 👍

**Comment by daiyam** [comment]
@R3uan3 After testing, if you use the setting `"explicitFolding.delay": 0,`, vscode should remember the collapsed regions...

The issue is that I'm adding a delay (by default) to register the folding provider so it have higher priority over builtin ones.
By doing so, when restoring the collapsed regions and since the provider isn't registered yet, vscode regenerate the folding regions...

**Comment by R3uan3** [comment]
Thank you! could I report one more 'issue'?
While editing a code if you delete one of the brackets the code move around and when you remove the second its 'returns', but returns to a different position.

**Comment by R3uan3** [comment]
@daiyam so? is this caused by the extension?

**Comment by daiyam** [comment]
@R3uan3 I don't think so since the extension is just reading the files and tell vscode where the foldings are. Then vscode merge all foldings and display them...

**Comment by R3uan3** [comment]
@daiyam could you teach me how to compile your extension?
I have never compiled or worked in any vscode extension before.

I have download `nodejs` and your extension src, then I install `npm`
execute cmd > cd  project folder > npm install package.json

what next? I'm completely lost, I wonder if you could guide me on this task 🙏

**Comment by daiyam** [comment]
In Visual Studio Code's menu, go to `View`/`Run`, then launch `Extension`.
It will run the extension in debug and prelaunch the task `npm: watch`.

**Comment by R3uan3** [comment]
Which extension? when I click view/run doesn't happen anything, could you be more specific please 🙏 I'm very beginner in this task.

**Comment by R3uan3** [comment]
@daiyam which extension? when I click view/run doesn't happen anything, could you be more specific please 🙏 I'm very beginner in this task.

**Comment by R3uan3** [comment]
How do you print something to the debug console?
i tried `console.log(var)` but I don't see anything in my console

**Comment by R3uan3** [comment]
@daiyam do you accept paid requests for editing vscode extensions? there's an extension that I would like to change some settings, if you do, can I have your contact then we can talk about it?

**Comment by daiyam** [comment]
You can contact me at daiyam@zokugun.org

**Comment by daiyam** [comment]
It should be resolved with [editor.defaultFoldingRangeProvider](https://github.com/zokugun/vscode-explicit-folding#editordefaultfoldingrangeprovider)
