### ISSUE TITLE
Can this help me get invisible comments?

### ISSUE THREAD

**Issue by icetbr** [zokugun/vscode-explicit-folding#81]
Hi there, given this code
```js
class A {
    /**
     * The Name
     */
    name,

    /** The Age  */
    age,
}
```

I want to get as close as possible to
```js
class A {
    name,
    age,
}
```

I'd appreciate any ideas. Thanks.

**Comment by daiyam** [comment]
Try:

```
"explicitFolding.rules": {
    "*": [
        {
            "begin": "/*",
            "end": "*/",
            "nested": false,
            "kind": "comment",
        },
    ],
},
```

You will be able to fold as:
```
class A {
    /**
    name,

    /** The Age  */
    age,
}
```

**Comment by icetbr** [comment]
I can get this without the extension, it's VsCode's default behavior.

**Comment by daiyam** [comment]
There is no way to completely hide a block of code/comment.

**Comment by icetbr** [comment]
Maybe, but I can get pretty close, if only I could get the new line regexes right.

```json
{
  "separator": ",",
},
```

```js
class A {
  /**...
  name,...
  age,
}
```

**Comment by icetbr** [comment]
Another idea, if you desire to have this as a feature, just return the folding region as line -= 1. Then I would get something like this

```js
class A {...
    name,...
    age,
}
```
