### ISSUE TITLE
Is possible to fold things in the same line?

### ISSUE THREAD

**Issue by derricck** [zokugun/vscode-explicit-folding#83]
Example:
https://stackoverflow.com/questions/72244103/possible-to-collapse-custom-regions

**Comment by daiyam** [comment]
Visual Studio Code doesn't support folding a single line.

**Comment by derricck** [comment]
@daiyam how to specify more than one `explicitFolding.rules` for the same language?

**Comment by daiyam** [comment]
I would try:
```
{
  "beginRegex": "]\\*.*$",
  "endRegex": "\\"$"
},
```

`\n` isn't recognized. The document parser is line-based. (cf https://github.com/zokugun/vscode-explicit-folding#faq)

You should also enable the debug https://github.com/zokugun/vscode-explicit-folding#debugging

**Comment by derricck** [comment]
Is possible to hide the gutter icon for a specific rule?

**Comment by daiyam** [comment]
I don't think so...

**Comment by derricck** [comment]
I have found this regex in one of your issues for `ahk`, when I add it, the first regex doesn't work anymore:

```ahk
    "[ahk]": {
        "explicitFolding.debug": false,
        "explicitFolding.rules": [
          {
            "beginRegex": "\\[\\d+,\\d+,\\d+,\\d+]\"",
            "endRegex": ";;",
          },
          {
            "kind": "comment",
            "beginRegex": "^\\s*\\/\\*",
            "endRegex": "\\*\\/",
            "nested": false
          },
          {
            "beginRegex": "\"(?:(?:[^\"]|\\\")*)(?=\")",
            "endRegex": "\""
          },
          {
            "begin": "{",
            "end": "}"
          }
        ]
    },
````
