### ISSUE TITLE
How to fold "if err != nil"

### ISSUE THREAD

**Issue by restfuladi** [zokugun/vscode-explicit-folding#85]
I would like to start with folding exactly this entire block:
```go
if err != nil {
   return err
}
```

If I use `"end": "}"` it catches other blocks but if I don't I can't get it to fold that last line. I guess `end` overrules `while` but I'm not sure how to have `while` look for more than one pattern. Thanks.

Config:
```
"explicitFolding.rules": {
        "go": [
            {
                "begin": "if err != nil",
                "whileRegex": "/return\serr/",
                "end": "}",
                "autoFold": true
            }
        ]
    }```

**Comment by daiyam** [comment]
Can you try:
```
"go": {
    "explicitFolding.rules": {
        "begin": "if err != nil",
        "whileRegex": "^\\s*(?:return\\serr|\\})",
        "autoFold": true,
    }
}
```

**Comment by restfuladi** [comment]
Thanks, I had the wrong `or` syntax.

**Comment by restfuladi** [comment]
Your code works well and it also gave me a few other ideas. Is there a way to re-process the folding on demand? I would be nice to get back to baseline with a keybind.

Thanks for a great extension!

**Comment by daiyam** [comment]
The foldings are reprocessed when you have updated the file or have changed the config.
