### ISSUE TITLE
Folding rules scoped for specific filenames?

### ISSUE THREAD

**Issue by daiyam** [zokugun/vscode-explicit-folding#87]
### Discussed in https://github.com/zokugun/vscode-explicit-folding/discussions/86

<div type='discussions-op-text'>

<sup>Originally posted by **depascalis** August 13, 2022</sup>
Is it possible to have folding rules that only apply to specific filenames like `*.special.js` or `*.special`? If not I would like to do a feature request if it is possible to implement.</div>

**Comment by daiyam** [comment]
@depascalis Yes, it's possible. I should able to implement it.

**Comment by depascalis** [comment]
Awesome, thank you @daiyam 
Btw the original question is still marked as unanswered. I don't know if this issue could be referenced as an answer for future reference.

**Comment by daiyam** [comment]
@depascalis I might be able to that with (not yet implemented):
```
"explicitFolding.rules": {
    "*.config.xml": [<your rules>],
    "*.special.js": [<your rules>],
},
```

Or you can create your own language as suggested by @aeschli.

**Comment by daiyam** [comment]
I will change to the following config:
```
"[javascript]": {
    "explicitFolding.perFiles": {
        "*.special.js": [<your rules>],
    },
},
"[xml]": {
    "explicitFolding.perFiles": {
        "*.config.xml": [<your rules>],
    },
},
```

**Comment by daiyam** [comment]
The feature is available in the latest release.

**Comment by daiyam** [comment]
@depascalis Can you close the issue if it's working for you 😉  Thx

**Comment by daiyam** [comment]
OH!
