### ISSUE TITLE
Prevent automatic unfold when moving the cursor down a line

### ISSUE THREAD

**Issue by ciwchris** [zokugun/vscode-explicit-folding#9]
After having folded a section when I cursor down it automatically unfolds the section. Is it possible to only automatically unfold the section if the cursor moves to the right (for left to right languages at least)?

**Comment by daiyam** [comment]
I don't have the issue.
Are you using a Vim extension? If yes, you might find a solution at https://github.com/aioutecism/amVim-for-VSCode/issues/184

**Comment by ciwchris** [comment]
I do. I had disabled it and reloaded the VS Code instance but it still behaved that way, although I had other VS Code instances still running. I just tried again, I disabled the vim extension and closed all instances and you are correct, the behavior is no longer occurring, so the issue you referenced looks to be my problem. Thank you for your prompt reply and for creating this extension.
