### ISSUE TITLE
nested nodes fail with regex. use syntax tree

### ISSUE THREAD

**Issue by milahu** [zokugun/vscode-explicit-folding#92]
let me use more powerful tools to select nodes

* syntax tree from tree-sitter
* syntax tree from lezer-parser
* xpath selectors for xml files
* css query for xml files
* ...

regex is too limited for this task

example:

```html
<div class="foldme">
  <div>inner 1</div>
  <div>inner 2</div>
</div>
```

result with folding:

```html
<div class="foldme">...
  <div>inner 2</div>
</div>
```

the last `</div>` cannot be matched with regex

settings

```json5
{
  "explicitFolding.rules": {
    "html": [
        // not working
        {
            "beginRegex": "<(?![a-z]+)(?:\\s+[^>]*)?\\s+class=(?:\"foldme\"|'foldme')",
            "endRegex": "<\\/\\1>",
            "autoFold": true
        },
        // note: meta has no close tag
        {
            "beginRegex": "<meta class=\"foldme\"",
            "endRegex": ">",
            "autoFold": true
        },

        // workaround for broken regex:
        // add some tags manually

        {
            "beginRegex": "<div class=\"foldme\"",
            "endRegex": "<\\/div>",
            "autoFold": true
        },
    ],
  },
  "explicitFolding.autoFold": "none",
}
```

**Comment by daiyam** [comment]
@milahu I agree that regex is limiting when try to fold a language but the primary objective of the extension is to support [user-specified folding](https://en.wikipedia.org/wiki/Code_folding#User-specified) (like `{{{ ... }}}`).

But to support folding based on a syntax tree is an all new kind of extension.

**Comment by milahu** [comment]
yeah ... im moving from vscode to [lapce](https://github.com/lapce/lapce) editor,
in the hope that they will base all plugins on parsers, not regex
(and multiple plugins share one parser, to avoid double-parsing)

there are tree-sitter plugins for vscode,
but i prefer a fast editor (rust vs javascript)

closing as "out of scope"

**Comment by daiyam** [comment]
lapce is still new. It still doesn't support folding since it uses the highlights from helix. 
How do you define foldings in tree-sitter? I'm interested because I find that the foldings definitions the VSCode's language grammar is very limited.

**Comment by milahu** [comment]
> How do you define foldings in tree-sitter?

based on the syntax tree...?

its just faster and more precise than regex, otherwise it should be similar.
sorry, i can only guess for now
