### ISSUE TITLE
Doesn't work in WSL

### ISSUE THREAD

**Issue by Atlinx** [zokugun/vscode-explicit-folding#93]
## Describe the issue

Folding doesn't work in WSL

### Running on WSL:
![image](https://user-images.githubusercontent.com/25368491/192423682-16554a0d-d4d8-4bc8-8f29-35c820505271.png)

![image](https://user-images.githubusercontent.com/25368491/192424062-57b7ea15-5e58-4a93-9286-503e950171d1.png)

### Running on Windows:

![image](https://user-images.githubusercontent.com/25368491/192424098-de84a6ba-f725-4750-92d7-0a3efea16365.png)

![image](https://user-images.githubusercontent.com/25368491/192424257-d27b7944-b13c-424b-8591-2d85bba9e4e5.png)

## To reproduce

- VSCode: 1.71.2
- Explicit Folding:  v0.21.1 (latest)
- Language: All languages

Open latest version of extension in WSL.

### Settings

```json
{
    "ocaml.sandbox": {
        "kind": "global"
    },
    "explicitFolding.rules": {
        "ocaml": [
            {
                "begin": "(* region",
                "end": "(* endregion"
            },
        ]
    }
}
```

## Expected behavior

Folding should work

**Comment by daiyam** [comment]
Yep! The extension must run in the Remote Extension Host to work. I've published the update. Thx
