### ISSUE TITLE
Is there any way of disabling function folding inside this plugin?

### ISSUE THREAD

**Issue by ramuyk** [zokugun/vscode-explicit-folding#94]
I use VSCode with the `Vim` plugin just so I'm able to use vim keybindings inside VSCode. I also use this Explicit folding extension to choose folding markers of my choice on the code. Everything works fine except that the function folding is not disabled when I activate the marker folding with the Explicit folding extension. 

The problem starts when I try to use these two Vim keybindings: 

```
zM- closes all foldings recursively
zR- opens all foldings recursively
```

Since the function folding is not deactivated, it doesn't matter how I organize my foldings with markers, `zM` will close all functions together with my markers and that will create more foldings than I want on my code. I'd like to find a way of deactivating the function folding on VSCode and leaving only the marker folding...  I know VSCode has a `folding` setting where I'm able to deactivate all foldings, but it'll also deactivate the Explicit Folding marker foldings if I deactivate it inside VSCode. Is there any configuration I can make with this extension to disable this default behavior of folding functions and leave only markers as the folding method?

## To reproduce

1.  Set : 

```
    "explicitFolding.rules": {
    "*": {
        "begin": "////",
        "end": "///"
    }
```

2.  Make the following `js` file:

```
function test(){
//// My code is doing something here
    console.log('test')
///
//// My code is doing another thing here
    console.log('test2')
///
}
```

3.  Install the [Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) extension.
4. Type `zM` and see that it'll fold the code twice: the first for the function and the second for the marker.

## Expected behavior
I'd like to find a way of making the foldings work only for markers... Not for functions (the default VSCode behavior)

## Screenshots

Desired behavior when I press `zM` with the sample of code that I gave:

![Screenshot_20221005_173700](https://user-images.githubusercontent.com/44415096/194158659-bdbfb224-b030-4723-ae0e-f55d390bb6ac.png)

Behavior that actually happens when I press `zM` with the sample of code that I gave:
![Screenshot_20221005_173650](https://user-images.githubusercontent.com/44415096/194158750-07007524-af5f-498c-9008-625592324898.png)

**Comment by daiyam** [comment]
@ramuyk no, it can't disable the foldings provided by the language. 
It's one of long standing issue with Visual Studio Code that I've tried to fix with:
- https://github.com/microsoft/vscode/pull/54200
- https://github.com/microsoft/vscode/pull/157434

This is why I have my own version that fix that issue.

**Comment by ramuyk** [comment]
@daiyam I see, is this change implemented in your main branch https://github.com/daiyam/vscode ?

**Comment by daiyam** [comment]
No, they are here: https://github.com/zokugun/MrCode

**Comment by daiyam** [comment]
It should be resolved with [editor.defaultFoldingRangeProvider](https://github.com/zokugun/vscode-explicit-folding#editordefaultfoldingrangeprovider)

**Comment by daiyam** [comment]
@ramuyk I'm assuming that the issue has been resolved.
